# Name your workflow
name: My test workflow

# Define the events that trigger the workflow
on: [push]

# Jobs run in parallel by default
jobs:

  # Job to print something
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -name: say hello
      run: echo "Hello, GitHub Actions!"

  # Job to build and test our C code
  build-and-test:
    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3


        # install nessary packages
      
      name: Install dependecies 
      run: sudo apt install -y build essential python3


      - run: pwd

      run: Run test
      run: python3 test.py